#!/bin/bash
set -ex

function run() {
    if ! command -v docker-compose &>/dev/null;then
        echo "CommandNotFound: docker-compose"
        exit 1
    fi

    cd ./deployment
    docker-compose up -d
}

function usage() {
    cat <<EOUSAGE
Usage: $(basename $0) [-h]
  -h                to show this help
EOUSAGE
}

function main() {
    while getopts "h" flag; do
        case ${flag} in
        h)
            usage
            exit 1function
            ;;
        esac
    done
}

main "$@"
