#!/bin/bash
set -ex

function usage() {
    cat <<EOUSAGE
Usage: $(basename $0) [-h] [-d] [-v]
  -h                to show this help
  -d                to detach docker processes
  -v                to remove volumes
EOUSAGE
}

function main() {
    CMD_UP="docker-compose up --build"
    CMD_DOWN="docker-compose down"

    while getopts "hdv" flag; do
        case ${flag} in
        d)
          CMD_UP="${CMD_UP} -d"
          ;;
        v)
          CMD_DOWN="${CMD_DOWN} -v"
          ;;
        h)
            usage
            exit 1
            ;;
        esac
    done

    if ! command -v docker-compose &>/dev/null;then
        echo "CommandNotFound: docker-compose"
        exit 1
    fi

    cd ./deployment
    docker-compose ps
    eval ${CMD_DOWN}
    eval ${CMD_UP}
    docker-compose ps
}

main "$@"
