#!/bin/bash
readonly CONTAINER="sql101_db"
readonly USER="postgres"
BLUE=$(tput setaf 4)
WHITE=$(tput sgr0)
RED=$(tput setaf 1)

function prints() {
    line="${1}"
    printf "${BLUE}${line}${WHITE}"
}

function printe() {
    line="${1}"
    printf "${RED}${line}${WHITE}\n"
    exit 1
}


function display_query() {
    quiz=${1}

    while IFS= read -r line; do
      if [ "${line}" == "/*" ];then
          prints "\nYour quiz:\n"
      elif [ "${line}" == "*/" ];then
          prints "\nYour query:\n"
      elif [ -n "${line}" ];then
          echo "${line}"
      fi
    done < "${quiz}"
}

function display_result() {
    command=${1}

    prints "\nYour result:\n"
    eval ${command}
}

function usage() {
    cat <<EOUSAGE
Usage: $(basename $0) [-h] [-q]
  -h                to show this help
  -q                to select quiz solution
EOUSAGE
}

function main() {
    CMD="docker exec -i ${CONTAINER} psql -U ${USER}"
    QUIZ=""

    while getopts "hq:s:" flag; do
        case ${flag} in
        q)
            QUIZ="./quiz/${OPTARG}.sql"
            ;;
        s)
            QUIZ="./solution/${OPTARG}.sql"
            ;;
        h)
            usage
            exit 1
            ;;
        esac
    done

    if [ -z ${QUIZ} ];then
      printe "Please select a quiz."
    fi
    if [ ! -f ${QUIZ} ];then
      printe "FileNotFound: ${QUIZ}"
    fi

    CMD="${CMD} < ${QUIZ}"
    prints "Execute command: ${CMD}\n"
    display_query "${QUIZ}"
    display_result "${CMD}"
}

main "$@"
