version: '3.1'

services:
  db:
    image: sql101_db
    container_name: sql101_db
    build:
        context: .
        dockerfile: db/Dockerfile
    volumes:
      - sql101_db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - "50000:5432"

  adminer:
    image: adminer
    container_name: sql101_adminer
    ports:
      - "50001:8080"

volumes:
  sql101_db_data:
